     /* ------------------------------------------------------------
         Country dial codes for the phone field — all 245 countries
         and territories, generated from libphonenumber (Google's
         numbering-plan metadata). Ukraine is pinned first (default);
         the rest are sorted alphabetically by Ukrainian name.
         `nsn` is the valid national-number length (digits after the
         code): a single number, or [min, max] where lengths vary.
         ------------------------------------------------------------ */
      var DIAL_CODES = [
        { flag: "🇺🇦", name: "Україна",                                   code: "+380", nsn: 9 },
        { flag: "🇦🇺", name: "Австралія",                                 code: "+61",  nsn: [5, 12] },
        { flag: "🇦🇹", name: "Австрія",                                   code: "+43",  nsn: [4, 13] },
        { flag: "🇦🇿", name: "Азербайджан",                               code: "+994", nsn: 9 },
        { flag: "🇦🇽", name: "Аландські Острови",                         code: "+358", nsn: [5, 12] },
        { flag: "🇦🇱", name: "Албанія",                                   code: "+355", nsn: [6, 9] },
        { flag: "🇩🇿", name: "Алжир",                                     code: "+213", nsn: [8, 9] },
        { flag: "🇦🇸", name: "Американське Самоа",                        code: "+1",   nsn: 10 },
        { flag: "🇦🇮", name: "Ангілья",                                   code: "+1",   nsn: 10 },
        { flag: "🇦🇴", name: "Ангола",                                    code: "+244", nsn: 9 },
        { flag: "🇦🇩", name: "Андорра",                                   code: "+376", nsn: [6, 9] },
        { flag: "🇦🇬", name: "Антигуа і Барбуда",                         code: "+1",   nsn: 10 },
        { flag: "🇦🇷", name: "Аргентина",                                 code: "+54",  nsn: [10, 11] },
        { flag: "🇦🇼", name: "Аруба",                                     code: "+297", nsn: 7 },
        { flag: "🇦🇫", name: "Афганістан",                                code: "+93",  nsn: 9 },
        { flag: "🇧🇸", name: "Багамські Острови",                         code: "+1",   nsn: 10 },
        { flag: "🇧🇩", name: "Бангладеш",                                 code: "+880", nsn: [6, 10] },
        { flag: "🇧🇧", name: "Барбадос",                                  code: "+1",   nsn: 10 },
        { flag: "🇧🇭", name: "Бахрейн",                                   code: "+973", nsn: 8 },
        { flag: "🇧🇿", name: "Беліз",                                     code: "+501", nsn: [7, 11] },
        { flag: "🇧🇪", name: "Бельгія",                                   code: "+32",  nsn: [8, 9] },
        { flag: "🇧🇯", name: "Бенін",                                     code: "+229", nsn: [8, 10] },
        { flag: "🇧🇲", name: "Бермудські Острови",                        code: "+1",   nsn: 10 },
        { flag: "🇧🇾", name: "Білорусь",                                  code: "+375", nsn: [6, 11] },
        { flag: "🇧🇬", name: "Болгарія",                                  code: "+359", nsn: [6, 12] },
        { flag: "🇧🇴", name: "Болівія",                                   code: "+591", nsn: [8, 9] },
        { flag: "🇧🇦", name: "Боснія і Герцеговина",                      code: "+387", nsn: [8, 9] },
        { flag: "🇧🇼", name: "Ботсвана",                                  code: "+267", nsn: [7, 10] },
        { flag: "🇧🇷", name: "Бразилія",                                  code: "+55",  nsn: [8, 11] },
        { flag: "🇮🇴", name: "Британська територія в Індійському океані", code: "+246", nsn: 7 },
        { flag: "🇻🇬", name: "Британські Віргінські острови",             code: "+1",   nsn: 10 },
        { flag: "🇧🇳", name: "Бруней",                                    code: "+673", nsn: 7 },
        { flag: "🇧🇫", name: "Буркіна-Фасо",                              code: "+226", nsn: 8 },
        { flag: "🇧🇮", name: "Бурунді",                                   code: "+257", nsn: 8 },
        { flag: "🇧🇹", name: "Бутан",                                     code: "+975", nsn: [7, 8] },
        { flag: "🇻🇺", name: "Вануату",                                   code: "+678", nsn: [5, 7] },
        { flag: "🇻🇦", name: "Ватикан",                                   code: "+39",  nsn: [6, 12] },
        { flag: "🇬🇧", name: "Велика Британія",                           code: "+44",  nsn: [7, 10] },
        { flag: "🇻🇪", name: "Венесуела",                                 code: "+58",  nsn: 10 },
        { flag: "🇻🇮", name: "Віргінські Острови (США)",                  code: "+1",   nsn: 10 },
        { flag: "🇦🇲", name: "Вірменія",                                  code: "+374", nsn: 8 },
        { flag: "🇻🇳", name: "Вʼєтнам",                                   code: "+84",  nsn: [7, 10] },
        { flag: "🇬🇦", name: "Габон",                                     code: "+241", nsn: [7, 8] },
        { flag: "🇭🇹", name: "Гаїті",                                     code: "+509", nsn: 8 },
        { flag: "🇬🇲", name: "Гамбія",                                    code: "+220", nsn: 7 },
        { flag: "🇬🇭", name: "Гана",                                      code: "+233", nsn: [8, 9] },
        { flag: "🇬🇾", name: "Гаяна",                                     code: "+592", nsn: 7 },
        { flag: "🇬🇵", name: "Гваделупа",                                 code: "+590", nsn: 9 },
        { flag: "🇬🇹", name: "Гватемала",                                 code: "+502", nsn: [8, 11] },
        { flag: "🇬🇳", name: "Гвінея",                                    code: "+224", nsn: [8, 9] },
        { flag: "🇬🇼", name: "Гвінея-Бісау",                              code: "+245", nsn: [7, 9] },
        { flag: "🇬🇬", name: "Гернсі",                                    code: "+44",  nsn: [7, 10] },
        { flag: "🇬🇮", name: "Гібралтар",                                 code: "+350", nsn: 8 },
        { flag: "🇭🇳", name: "Гондурас",                                  code: "+504", nsn: [8, 11] },
        { flag: "🇭🇰", name: "Гонконг, ОАР Китаю",                        code: "+852", nsn: [5, 11] },
        { flag: "🇬🇩", name: "Гренада",                                   code: "+1",   nsn: 10 },
        { flag: "🇬🇱", name: "Гренландія",                                code: "+299", nsn: 6 },
        { flag: "🇬🇷", name: "Греція",                                    code: "+30",  nsn: [10, 12] },
        { flag: "🇬🇪", name: "Грузія",                                    code: "+995", nsn: 9 },
        { flag: "🇬🇺", name: "Гуам",                                      code: "+1",   nsn: 10 },
        { flag: "🇩🇰", name: "Данія",                                     code: "+45",  nsn: 8 },
        { flag: "🇯🇪", name: "Джерсі",                                    code: "+44",  nsn: 10 },
        { flag: "🇩🇯", name: "Джибуті",                                   code: "+253", nsn: 8 },
        { flag: "🇩🇲", name: "Домініка",                                  code: "+1",   nsn: 10 },
        { flag: "🇩🇴", name: "Домініканська Республіка",                  code: "+1",   nsn: 10 },
        { flag: "🇪🇨", name: "Еквадор",                                   code: "+593", nsn: [8, 11] },
        { flag: "🇬🇶", name: "Екваторіальна Гвінея",                      code: "+240", nsn: 9 },
        { flag: "🇪🇷", name: "Еритрея",                                   code: "+291", nsn: 7 },
        { flag: "🇸🇿", name: "Есватіні",                                  code: "+268", nsn: [8, 9] },
        { flag: "🇪🇪", name: "Естонія",                                   code: "+372", nsn: [7, 10] },
        { flag: "🇪🇹", name: "Ефіопія",                                   code: "+251", nsn: 9 },
        { flag: "🇪🇬", name: "Єгипет",                                    code: "+20",  nsn: [8, 10] },
        { flag: "🇾🇪", name: "Ємен",                                      code: "+967", nsn: [7, 9] },
        { flag: "🇿🇲", name: "Замбія",                                    code: "+260", nsn: 9 },
        { flag: "🇪🇭", name: "Західна Сахара",                            code: "+212", nsn: 9 },
        { flag: "🇿🇼", name: "Зімбабве",                                  code: "+263", nsn: [5, 10] },
        { flag: "🇮🇱", name: "Ізраїль",                                   code: "+972", nsn: [7, 12] },
        { flag: "🇮🇳", name: "Індія",                                     code: "+91",  nsn: [8, 13] },
        { flag: "🇮🇩", name: "Індонезія",                                 code: "+62",  nsn: [7, 17] },
        { flag: "🇮🇶", name: "Ірак",                                      code: "+964", nsn: [8, 10] },
        { flag: "🇮🇷", name: "Іран",                                      code: "+98",  nsn: [4, 10] },
        { flag: "🇮🇪", name: "Ірландія",                                  code: "+353", nsn: [7, 10] },
        { flag: "🇮🇸", name: "Ісландія",                                  code: "+354", nsn: [7, 9] },
        { flag: "🇪🇸", name: "Іспанія",                                   code: "+34",  nsn: 9 },
        { flag: "🇮🇹", name: "Італія",                                    code: "+39",  nsn: [6, 12] },
        { flag: "🇯🇴", name: "Йорданія",                                  code: "+962", nsn: [8, 9] },
        { flag: "🇨🇻", name: "Кабо-Верде",                                code: "+238", nsn: 7 },
        { flag: "🇰🇿", name: "Казахстан",                                 code: "+7",   nsn: [10, 14] },
        { flag: "🇰🇾", name: "Кайманові Острови",                         code: "+1",   nsn: 10 },
        { flag: "🇰🇭", name: "Камбоджа",                                  code: "+855", nsn: [8, 10] },
        { flag: "🇨🇲", name: "Камерун",                                   code: "+237", nsn: [8, 9] },
        { flag: "🇨🇦", name: "Канада",                                    code: "+1",   nsn: [7, 10] },
        { flag: "🇧🇶", name: "Карибські Нідерланди",                      code: "+599", nsn: 7 },
        { flag: "🇶🇦", name: "Катар",                                     code: "+974", nsn: [7, 11] },
        { flag: "🇰🇪", name: "Кенія",                                     code: "+254", nsn: [7, 10] },
        { flag: "🇰🇬", name: "Киргизстан",                                code: "+996", nsn: [9, 10] },
        { flag: "🇨🇳", name: "Китай",                                     code: "+86",  nsn: [7, 12] },
        // { flag: "🇨🇾", name: "Кіпр",                                      code: "+357", nsn: 8 },
        { flag: "🇰🇮", name: "Кірибаті",                                  code: "+686", nsn: [5, 8] },
        { flag: "🇨🇨", name: "Кокосові (Кілінг) Острови",                 code: "+61",  nsn: [6, 12] },
        { flag: "🇨🇴", name: "Колумбія",                                  code: "+57",  nsn: [8, 11] },
        { flag: "🇰🇲", name: "Комори",                                    code: "+269", nsn: 7 },
        { flag: "🇨🇬", name: "Конго – Браззавіль",                        code: "+242", nsn: 9 },
        { flag: "🇨🇩", name: "Конго – Кіншаса",                           code: "+243", nsn: [7, 10] },
        { flag: "🇽🇰", name: "Косово",                                    code: "+383", nsn: [8, 12] },
        { flag: "🇨🇷", name: "Коста-Рика",                                code: "+506", nsn: [8, 10] },
        { flag: "🇨🇮", name: "Кот-дʼІвуар",                               code: "+225", nsn: 10 },
        { flag: "🇨🇺", name: "Куба",                                      code: "+53",  nsn: [6, 10] },
        { flag: "🇰🇼", name: "Кувейт",                                    code: "+965", nsn: [7, 8] },
        { flag: "🇨🇼", name: "Кюрасао",                                   code: "+599", nsn: [7, 8] },
        { flag: "🇱🇦", name: "Лаос",                                      code: "+856", nsn: [8, 10] },
        { flag: "🇱🇻", name: "Латвія",                                    code: "+371", nsn: 8 },
        { flag: "🇱🇸", name: "Лесото",                                    code: "+266", nsn: 8 },
        { flag: "🇱🇹", name: "Литва",                                     code: "+370", nsn: 8 },
        { flag: "🇱🇷", name: "Ліберія",                                   code: "+231", nsn: [7, 9] },
        { flag: "🇱🇧", name: "Ліван",                                     code: "+961", nsn: [7, 8] },
        { flag: "🇱🇾", name: "Лівія",                                     code: "+218", nsn: 9 },
        { flag: "🇱🇮", name: "Ліхтенштейн",                               code: "+423", nsn: [7, 9] },
        { flag: "🇱🇺", name: "Люксембург",                                code: "+352", nsn: [4, 11] },
        { flag: "🇲🇺", name: "Маврикій",                                  code: "+230", nsn: [7, 10] },
        { flag: "🇲🇷", name: "Мавританія",                                code: "+222", nsn: 8 },
        { flag: "🇲🇬", name: "Мадагаскар",                                code: "+261", nsn: 9 },
        { flag: "🇾🇹", name: "Майотта",                                   code: "+262", nsn: 9 },
        { flag: "🇲🇴", name: "Макао, ОАР Китаю",                          code: "+853", nsn: [7, 8] },
        { flag: "🇲🇼", name: "Малаві",                                    code: "+265", nsn: [7, 9] },
        { flag: "🇲🇾", name: "Малайзія",                                  code: "+60",  nsn: [8, 10] },
        { flag: "🇲🇱", name: "Малі",                                      code: "+223", nsn: 8 },
        { flag: "🇲🇻", name: "Мальдіви",                                  code: "+960", nsn: [7, 10] },
        { flag: "🇲🇹", name: "Мальта",                                    code: "+356", nsn: 8 },
        { flag: "🇲🇦", name: "Марокко",                                   code: "+212", nsn: 9 },
        { flag: "🇲🇶", name: "Мартиніка",                                 code: "+596", nsn: 9 },
        { flag: "🇲🇭", name: "Маршаллові Острови",                        code: "+692", nsn: 7 },
        { flag: "🇲🇽", name: "Мексика",                                   code: "+52",  nsn: 10 },
        { flag: "🇫🇲", name: "Мікронезія",                                code: "+691", nsn: 7 },
        { flag: "🇲🇿", name: "Мозамбік",                                  code: "+258", nsn: [8, 9] },
        { flag: "🇲🇩", name: "Молдова",                                   code: "+373", nsn: 8 },
        { flag: "🇲🇨", name: "Монако",                                    code: "+377", nsn: [8, 9] },
        { flag: "🇲🇳", name: "Монголія",                                  code: "+976", nsn: [8, 10] },
        { flag: "🇲🇸", name: "Монтсеррат",                                code: "+1",   nsn: 10 },
        { flag: "🇲🇲", name: "Мʼянма (Бірма)",                            code: "+95",  nsn: [6, 10] },
        { flag: "🇳🇦", name: "Намібія",                                   code: "+264", nsn: [8, 9] },
        { flag: "🇳🇷", name: "Науру",                                     code: "+674", nsn: 7 },
        { flag: "🇳🇵", name: "Непал",                                     code: "+977", nsn: [8, 11] },
        { flag: "🇳🇪", name: "Нігер",                                     code: "+227", nsn: 8 },
        { flag: "🇳🇬", name: "Нігерія",                                   code: "+234", nsn: [10, 14] },
        { flag: "🇳🇱", name: "Нідерланди",                                code: "+31",  nsn: [5, 11] },
        { flag: "🇳🇮", name: "Нікарагуа",                                 code: "+505", nsn: 8 },
        { flag: "🇩🇪", name: "Німеччина",                                 code: "+49",  nsn: [4, 15] },
        { flag: "🇳🇺", name: "Ніуе",                                      code: "+683", nsn: [4, 7] },
        { flag: "🇳🇿", name: "Нова Зеландія",                             code: "+64",  nsn: [5, 10] },
        { flag: "🇳🇨", name: "Нова Каледонія",                            code: "+687", nsn: 6 },
        { flag: "🇳🇴", name: "Норвегія",                                  code: "+47",  nsn: [5, 8] },
        { flag: "🇦🇪", name: "Обʼєднані Арабські Емірати",                code: "+971", nsn: [5, 12] },
        { flag: "🇴🇲", name: "Оман",                                      code: "+968", nsn: [7, 9] },
        { flag: "🇦🇨", name: "Острів Вознесіння",                         code: "+247", nsn: [5, 6] },
        { flag: "🇮🇲", name: "Острів Мен",                                code: "+44",  nsn: 10 },
        { flag: "🇳🇫", name: "Острів Норфолк",                            code: "+672", nsn: 6 },
        { flag: "🇨🇽", name: "Острів Різдва",                             code: "+61",  nsn: [6, 12] },
        { flag: "🇸🇭", name: "Острів Святої Єлени",                       code: "+290", nsn: [4, 5] },
        { flag: "🇨🇰", name: "Острови Кука",                              code: "+682", nsn: 5 },
        { flag: "🇹🇨", name: "Острови Теркс і Кайкос",                    code: "+1",   nsn: 10 },
        { flag: "🇵🇰", name: "Пакистан",                                  code: "+92",  nsn: [8, 12] },
        { flag: "🇵🇼", name: "Палау",                                     code: "+680", nsn: 7 },
        { flag: "🇵🇸", name: "Палестинські території",                    code: "+970", nsn: [8, 10] },
        { flag: "🇵🇦", name: "Панама",                                    code: "+507", nsn: [7, 11] },
        { flag: "🇵🇬", name: "Папуа-Нова Гвінея",                         code: "+675", nsn: [7, 8] },
        { flag: "🇵🇾", name: "Парагвай",                                  code: "+595", nsn: [6, 11] },
        { flag: "🇵🇪", name: "Перу",                                      code: "+51",  nsn: [8, 9] },
        { flag: "🇰🇷", name: "Південна Корея",                            code: "+82",  nsn: [5, 14] },
        { flag: "🇸🇸", name: "Південний Судан",                           code: "+211", nsn: 9 },
        { flag: "🇿🇦", name: "Південно-Африканська Республіка",           code: "+27",  nsn: [5, 10] },
        { flag: "🇰🇵", name: "Північна Корея",                            code: "+850", nsn: [8, 10] },
        { flag: "🇲🇰", name: "Північна Македонія",                        code: "+389", nsn: 8 },
        { flag: "🇲🇵", name: "Північні Маріанські Острови",               code: "+1",   nsn: 10 },
        // { flag: "🇵🇱", name: "Польща",                                    code: "+48",  nsn: [6, 10] },
        { flag: "🇵🇹", name: "Португалія",                                code: "+351", nsn: 9 },
        { flag: "🇵🇷", name: "Пуерто-Рико",                               code: "+1",   nsn: 10 },
        { flag: "🇷🇪", name: "Реюньйон",                                  code: "+262", nsn: 9 },
        // { flag: "🇷🇺", name: "Росія",                                     code: "+7",   nsn: [10, 14] },
        { flag: "🇷🇼", name: "Руанда",                                    code: "+250", nsn: [8, 9] },
        { flag: "🇷🇴", name: "Румунія",                                   code: "+40",  nsn: [6, 9] },
        { flag: "🇸🇻", name: "Сальвадор",                                 code: "+503", nsn: [7, 11] },
        { flag: "🇼🇸", name: "Самоа",                                     code: "+685", nsn: [5, 10] },
        { flag: "🇸🇲", name: "Сан-Марино",                                code: "+378", nsn: [8, 10] },
        { flag: "🇸🇹", name: "Сан-Томе і Принсіпі",                       code: "+239", nsn: 7 },
        { flag: "🇸🇦", name: "Саудівська Аравія",                         code: "+966", nsn: [9, 10] },
        { flag: "🇸🇨", name: "Сейшельські Острови",                       code: "+248", nsn: 7 },
        { flag: "🇧🇱", name: "Сен-Бартелемі",                             code: "+590", nsn: 9 },
        { flag: "🇲🇫", name: "Сен-Мартен",                                code: "+590", nsn: 9 },
        { flag: "🇵🇲", name: "Сен-Пʼєр і Мікелон",                        code: "+508", nsn: [6, 9] },
        { flag: "🇸🇳", name: "Сенегал",                                   code: "+221", nsn: 9 },
        { flag: "🇻🇨", name: "Сент-Вінсент і Гренадіни",                  code: "+1",   nsn: 10 },
        { flag: "🇰🇳", name: "Сент-Кітс і Невіс",                         code: "+1",   nsn: 10 },
        { flag: "🇱🇨", name: "Сент-Люсія",                                code: "+1",   nsn: 10 },
        { flag: "🇷🇸", name: "Сербія",                                    code: "+381", nsn: [6, 12] },
        { flag: "🇸🇾", name: "Сирія",                                     code: "+963", nsn: [8, 9] },
        { flag: "🇸🇬", name: "Сінгапур",                                  code: "+65",  nsn: [8, 11] },
        { flag: "🇸🇽", name: "Сінт-Мартен",                               code: "+1",   nsn: 10 },
        { flag: "🇸🇰", name: "Словаччина",                                code: "+421", nsn: [6, 9] },
        { flag: "🇸🇮", name: "Словенія",                                  code: "+386", nsn: [5, 8] },
        { flag: "🇸🇧", name: "Соломонові Острови",                        code: "+677", nsn: [5, 7] },
        { flag: "🇸🇴", name: "Сомалі",                                    code: "+252", nsn: [6, 9] },
        { flag: "🇺🇸", name: "Сполучені Штати",                           code: "+1",   nsn: 10 },
        { flag: "🇸🇩", name: "Судан",                                     code: "+249", nsn: 9 },
        { flag: "🇸🇷", name: "Суринам",                                   code: "+597", nsn: [6, 7] },
        { flag: "🇸🇱", name: "Сьєрра-Леоне",                              code: "+232", nsn: 8 },
        { flag: "🇹🇯", name: "Таджикистан",                               code: "+992", nsn: 9 },
        { flag: "🇹🇭", name: "Таїланд",                                   code: "+66",  nsn: [8, 13] },
        { flag: "🇹🇼", name: "Тайвань",                                   code: "+886", nsn: [7, 11] },
        { flag: "🇹🇿", name: "Танзанія",                                  code: "+255", nsn: 9 },
        { flag: "🇹🇱", name: "Тимор-Лешті",                               code: "+670", nsn: [7, 8] },
        { flag: "🇹🇬", name: "Того",                                      code: "+228", nsn: 8 },
        { flag: "🇹🇰", name: "Токелау",                                   code: "+690", nsn: [4, 7] },
        { flag: "🇹🇴", name: "Тонга",                                     code: "+676", nsn: [5, 7] },
        { flag: "🇹🇹", name: "Тринідад і Тобаго",                         code: "+1",   nsn: 10 },
        { flag: "🇹🇦", name: "Трістан-да-Кунья",                          code: "+290", nsn: 4 },
        { flag: "🇹🇻", name: "Тувалу",                                    code: "+688", nsn: [5, 7] },
        { flag: "🇹🇳", name: "Туніс",                                     code: "+216", nsn: 8 },
        { flag: "🇹🇷", name: "Туреччина",                                 code: "+90",  nsn: [7, 13] },
        { flag: "🇹🇲", name: "Туркменістан",                              code: "+993", nsn: 8 },
        { flag: "🇺🇬", name: "Уганда",                                    code: "+256", nsn: 9 },
        { flag: "🇭🇺", name: "Угорщина",                                  code: "+36",  nsn: [8, 9] },
        { flag: "🇺🇿", name: "Узбекистан",                                code: "+998", nsn: 9 },
        { flag: "🇼🇫", name: "Уолліс і Футуна",                           code: "+681", nsn: [6, 9] },
        { flag: "🇺🇾", name: "Уругвай",                                   code: "+598", nsn: [4, 13] },
        { flag: "🇫🇴", name: "Фарерські Острови",                         code: "+298", nsn: 6 },
        { flag: "🇫🇯", name: "Фіджі",                                     code: "+679", nsn: [7, 11] },
        { flag: "🇵🇭", name: "Філіппіни",                                 code: "+63",  nsn: [6, 13] },
        { flag: "🇫🇮", name: "Фінляндія",                                 code: "+358", nsn: [5, 12] },
        { flag: "🇫🇰", name: "Фолклендські Острови",                      code: "+500", nsn: 5 },
        { flag: "🇫🇷", name: "Франція",                                   code: "+33",  nsn: 9 },
        { flag: "🇬🇫", name: "Французька Гвіана",                         code: "+594", nsn: 9 },
        { flag: "🇵🇫", name: "Французька Полінезія",                      code: "+689", nsn: [6, 9] },
        { flag: "🇭🇷", name: "Хорватія",                                  code: "+385", nsn: [7, 9] },
        { flag: "🇨🇫", name: "Центральноафриканська Республіка",          code: "+236", nsn: 8 },
        { flag: "🇹🇩", name: "Чад",                                       code: "+235", nsn: 8 },
        { flag: "🇨🇿", name: "Чехія",                                     code: "+420", nsn: [9, 12] },
        { flag: "🇨🇱", name: "Чилі",                                      code: "+56",  nsn: [9, 11] },
        { flag: "🇲🇪", name: "Чорногорія",                                code: "+382", nsn: [8, 9] },
        { flag: "🇨🇭", name: "Швейцарія",                                 code: "+41",  nsn: [9, 12] },
        { flag: "🇸🇪", name: "Швеція",                                    code: "+46",  nsn: [6, 12] },
        { flag: "🇸🇯", name: "Шпіцберген та Ян-Маєн",                     code: "+47",  nsn: [5, 8] },
        { flag: "🇱🇰", name: "Шрі-Ланка",                                 code: "+94",  nsn: 9 },
        { flag: "🇯🇲", name: "Ямайка",                                    code: "+1",   nsn: 10 },
        { flag: "🇯🇵", name: "Японія",                                    code: "+81",  nsn: [8, 17] }
      ];
